# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KG620AUwrbeYZOOopbgO-suUTLDfDUgS
"""

# Pandas
# Word on Data Set
import pandas as pd
df = pd.read_excel('nyc_weather.xlsx')
df

print(df['Temperature'].max())
print(df['Temperature'].min())

df[['EST','Humidity']][df['Events'] == 'Rain']

df.fillna(0,inplace=True)

df.loc[(df['Humidity'] >= 40) & (df['Events'] == 'Rain'), ['EST', 'Events' , 'Humidity']]

"""# Using Dictionary:

---


"""

Data = {
    'Name' : ['Muhammad' , 'Ali' , 'Aliyaan' , 'raahim'],
    'Sid' : ['15437' , '15438' , '15439' , '15440'],
    'Course' : ['PF' , 'OOP' , 'DSA' , 'DBMS']
}

data_set = pd.DataFrame(Data)
data_set

"""# Using List Dictionary:

---


"""

Values = [
    {'Name' : 'Muhammad' , 'Sid' :	'15437' , 'Course' :	'PF' },
    {'Name' : 'Ali' , 'Sid' :	'15438' , 'Course' :	'OOP' },
    {'Name' : 'Aliyaan' , 'Sid' :	'15439' , 'Course' :	'DSA' },
    {'Name' : 'Raahim' , 'Sid' :	'15440' , 'Course' :	'DBMS' }
]

list_Dic = pd.DataFrame(Values)
list_Dic

